server:
  port: 8082

spring:
  application:
    name: payment-service

  datasource:
    url: jdbc:h2:mem:paymentdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: payment-service-group

management:
  endpoints:
    web:
      exposure:
        include: health,info
