server:
  port: 8082

spring:
  application:
    name: payment-service

  datasource:
    url: jdbc:postgresql://localhost:5432/payment_db
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: payment-service-group

management:
  endpoints:
    web:
      exposure:
        include: health,info
